# Generated by Django 5.2.4 on 2025-08-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('stock_Quantity', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
