# Generated by Django 5.2.4 on 2025-08-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produt',
            new_name='Product',
        ),
    ]
